service: happy-meal

useDotenv: true
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  endpointType: EDGE

  memorySize: ${param:memorySize}
  timeout: ${param:timeout}
  logRetentionInDays: ${param:logRetentionInDays}

  environment:
    STAGE: ${self:provider.stage}


params:
  dev:
    memorySize: 128
    timeout: 29
    logRetentionInDays: 7
  prod:
    memorySize: 128 #will change later if needed
    timeout: 29
    logRetentionInDays: 14

custom:
  dotenv:
    # Automatically load correct file based on stage
    path: .env.${self:provider.stage}

package:
  patterns:
    - "!./**"
    - "./bootstrap"

functions:
  handler:
    name: ${self:service}-${self:provider.stage}
    handler: bootstrap
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}
